version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: my_service_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
  node_app:
    build: ./node-app
    restart: always
      - "3001:3001"
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: my_service_db
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3001
      MOCK_MIN_DELAY_MS: 50
      MOCK_MAX_DELAY_MS: 500
    depends_on:
      - db

volumes:
  db_data: