global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node_app:3001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']